# Generated by Django 5.2.10 on 2026-01-20 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código/SKU')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('date_claim', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('status', models.CharField(choices=[('OP', 'Abierta'), ('PR', 'En Proceso'), ('CL', 'Finalizada')], default='OP', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='users.product')),
            ],
            options={
                'verbose_name': 'Reclamación',
                'verbose_name_plural': 'Reclamaciones',
            },
        ),
    ]
