# Generated by Django 5.0.6 on 2024-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="motive",
            field=models.CharField(
                choices=[
                    ("S", "Internet"),
                    ("H", "Mobile"),
                    ("L", "TV"),
                    ("O", "Other"),
                ],
                max_length=2,
            ),
        ),
    ]
