# Generated by Django 5.0.6 on 2024-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
