# Generated by Django 5.0.6 on 2024-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_client_motive"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="title",
            field=models.CharField(
                help_text="Title of your problem", max_length=40, null=True
            ),
        ),
    ]
