# Generated by Django 5.0.6 on 2024-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_product_price_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="date_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
